name: flutter_pokemon_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - 'assets/'
  fonts:
    - family: PokemonSolid
      fonts:
        - asset: 'assets/fonts/Pokemon-Solid.ttf'
